"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load the environment variables
load_dotenv()

# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

WEB_DOMAIN = os.getenv('WEB_DOMAIN') if not DEBUG else 'localhost:8000'  # The domain is the local machine in dev

ALLOWED_HOSTS = [WEB_DOMAIN, 'localhost', '127.0.0.1']

GITHUB_REPO = 'https://github.com/ilwan07/OuiTransfer/'

OWNER = 'Ilwân'  # Your name here

BASE_STORAGE_PATH = '/home/ilwan/tests/transfers/'  # Default path to store transfered files (must be allowed, see below)
ALLOW_DOTFILES = False  # Whether to show and allow dotted directories

# Only allow to save files in directories under these paths (include trailing slashes)
# Each couple is the path and its alias name (CANNOT contain a '/', can be None)
# SECURITY WARNING: don't include any sensitive path, edit this!
ALLOWED_STORAGE_ROOTS = [
    ('/home/ilwan/', 'Home'),
    ('/mnt/nas/', 'NAS'),
    ('/var/tmp/', None),
    ('/tmp/', 'TMP'),
]

STORAGE_SAFE_SPACE = 2 * 2**30  # Consider storage full if less than this space is free (in bytes)
UPLOAD_CHUNK_SIZE = 5 * 2**20  # Size of each chunk to upload
UPLOAD_TIMEOUT = 10 * 60  # How many seconds after last chunk received to consider an upload/share to be cancelled

USE_ANTIVIRUS = True  # Scan uploaded files witch clamav
ANTIVIRUS_MAX_SIZE = 1 * 2**30  # Size limit to perform antivirus scan
# antivirus notes: use --fdpass for read access, enable AlertExceedsMax in config, change MaxFileSize and MaxScanSize in config

# Email configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('AGENT_EMAIL')
CONTACT_EMAIL = os.getenv('CONTACT_EMAIL')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'ouitransfer.apps.OuitransferConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ouitransfer.context_processors.context_values',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Logging
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "ouitransfer.log",
            "maxBytes": 10 * 2**20,
            "backupCount": 5,
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "DEBUG",
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password hashing functions

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    #'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    #'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    #'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    #'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Jobs

CRONJOBS = [
    ('*/5 * * * *', 'ouitransfer.jobs.myjob')  # run job every 5min
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ("en", "English"),
    ("fr", "Français"),
]

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path('/var/www/ouitransfer/static')


# SECURITY WARNING: uncomment these lines in production

#SECURE_SSL_REDIRECT = True
#SECURE_HSTS_SECONDS = 31536000  # 1 year
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
